version: "3"

services:
  app:
    build: ./app
    ports:
      - "3111:3111"
    depends_on:
      - sql

  sql:
    build: ./sql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: snltdb
      MARIADB_USER: snlt
      MARIADB_PASSWORD: snlt01
      TZ: "Asia/Tokyo"
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
      - ./sql/data:/var/lib/mysql
    container_name: sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - sql
